CREATE TABLE gestiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP NOT NULL,
    resultado VARCHAR(20) NOT NULL,
    observacion VARCHAR(255),

    deuda_id BIGINT NOT NULL,
    accion_id BIGINT NOT NULL,

    CONSTRAINT fk_gestion_deuda
        FOREIGN KEY (deuda_id)
        REFERENCES deuda(id),

        CONSTRAINT fk_gestion_accion
            FOREIGN KEY (accion_id)
            REFERENCES acciones(id)
);