-- Deuda vencida por padrón (CM), cargada desde GeoPagos /facturas/pendientes
CREATE TABLE deuda (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cm                      VARCHAR(30)    NOT NULL,
    numero_padron           VARCHAR(30)    NOT NULL,
    block                   VARCHAR(30),
    unidad                  VARCHAR(30),
    localidad               VARCHAR(100),
    padtipo                 VARCHAR(10),
    contribuyente_nombre    VARCHAR(200),
    contribuyente_documento VARCHAR(30),
    tributos                VARCHAR(200),
    importe                 NUMERIC(15, 2),
    deuda_desde             DATE,
    ultimo_vencimiento      DATE,
    anios_deuda             VARCHAR(200),
    convenio                BOOLEAN        NOT NULL DEFAULT FALSE,
    estado                  VARCHAR(20)    NOT NULL,
    fecha_sincronizacion    TIMESTAMP,
    fecha_creacion          TIMESTAMP      NOT NULL,
    fecha_actualizacion     TIMESTAMP      NOT NULL,
    CONSTRAINT uk_deuda_cm UNIQUE (cm),
    CONSTRAINT ck_deuda_estado CHECK (estado IN ('PENDIENTE', 'EN_GESTION', 'EN_CONVENIO', 'CANCELADA'))
);

CREATE INDEX idx_deuda_numero_padron ON deuda (numero_padron);
CREATE INDEX idx_deuda_estado ON deuda (estado);
CREATE INDEX idx_deuda_deuda_desde ON deuda (deuda_desde);
CREATE INDEX idx_deuda_contribuyente_documento ON deuda (contribuyente_documento);
