-- Catálogo de tributos y relación con las deudas.
-- Reemplaza la columna de texto deuda.tributos ("101, 3802") por una relación real.

CREATE TABLE tributos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(20)  NOT NULL,
    descripcion VARCHAR(200),
    CONSTRAINT uk_tributos_codigo UNIQUE (codigo)
);

CREATE TABLE deuda_tributo (
    deuda_id   BIGINT NOT NULL,
    tributo_id BIGINT NOT NULL,
    CONSTRAINT pk_deuda_tributo PRIMARY KEY (deuda_id, tributo_id),
    CONSTRAINT fk_deuda_tributo_deuda FOREIGN KEY (deuda_id) REFERENCES deuda (id) ON DELETE CASCADE,
    CONSTRAINT fk_deuda_tributo_tributo FOREIGN KEY (tributo_id) REFERENCES tributos (id)
);

CREATE INDEX idx_deuda_tributo_tributo_id ON deuda_tributo (tributo_id);

-- La tabla deuda todavía no tiene datos: no hay nada que migrar desde la columna de texto
ALTER TABLE deuda DROP COLUMN tributos;

-- Códigos definidos en la Política de Gestión de la Morosidad.
-- Las descripciones no vienen en la API de GeoPagos: quedan para completar por el Administrador.
-- Los códigos de Concesiones (FAC) no están listados en la política: se agregan al sincronizar.
INSERT INTO tributos (codigo) VALUES
    ('101'),   -- CIR
    ('201'),   -- CIU
    ('301'),   -- CIU
    ('801'),   -- Impuesto Ley 12.700
    ('802'),   -- Impuesto Ley 12.700
    ('2401'),  -- CIU
    ('3101'),  -- CIU
    ('3801'),  -- CIU
    ('3802'),  -- CIR
    ('7502'),  -- Hogar estudiantil
    ('7503'),  -- Hogar estudiantil
    ('10206'), -- Instituciones Piscina Fraternidad
    ('35701'); -- Impuesto Ley 12.700
