-- Segmentos de morosidad y sus rangos de días configurables (CU Configurar períodos de mora).

CREATE TABLE segmentos_mora (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(50)  NOT NULL,
    descripcion VARCHAR(500),
    orden       INTEGER      NOT NULL,
    CONSTRAINT uk_segmentos_mora_nombre UNIQUE (nombre)
);

-- Rango de días de atraso de cada segmento. Solo una configuración activa por segmento:
-- al cambiar un rango se desactiva la anterior y queda el historial (quién cambió qué y cuándo).
CREATE TABLE configuraciones_segmento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segmento_mora_id BIGINT    NOT NULL,
    dias_desde       INTEGER   NOT NULL,
    dias_hasta       INTEGER,            -- NULL = sin tope (ej. Mora Tardía)
    activa           BOOLEAN   NOT NULL DEFAULT TRUE,
    fecha_creacion   TIMESTAMP NOT NULL,
    CONSTRAINT fk_configuracion_segmento FOREIGN KEY (segmento_mora_id) REFERENCES segmentos_mora (id),
    CONSTRAINT ck_configuracion_dias CHECK (dias_desde >= 0 AND (dias_hasta IS NULL OR dias_hasta >= dias_desde))
);

CREATE UNIQUE INDEX uk_configuracion_activa_por_segmento
    ON configuraciones_segmento (segmento_mora_id) WHERE activa;

-- Segmento asignado automáticamente y último cobro informado por GeoPagos
ALTER TABLE deuda
    ADD COLUMN segmento_mora_id      BIGINT,
    ADD COLUMN fecha_ultimo_cobro    DATE,
    ADD COLUMN importe_ultimo_cobro  NUMERIC(15, 2),
    ADD CONSTRAINT fk_deuda_segmento_mora FOREIGN KEY (segmento_mora_id) REFERENCES segmentos_mora (id);

CREATE INDEX idx_deuda_segmento_mora_id ON deuda (segmento_mora_id);

-- Segmentos iniciales (Política de Gestión de la Morosidad)
INSERT INTO segmentos_mora (nombre, descripcion, orden) VALUES
    ('Mora Temprana', 'Se atrasaron, pero no son morosos estructurales. Objetivo: regularizar rápido sin generar conflicto.', 1),
    ('Mora Inicial',  'Deuda más persistente, comportamiento irregular o reiteración de atrasos. Objetivo: lograr regularización.', 2),
    ('Mora Tardía',   'Deudas antiguas con bajo nivel de respuesta espontánea. Objetivo: maximizar la recuperación posible.', 3);

INSERT INTO configuraciones_segmento (segmento_mora_id, dias_desde, dias_hasta, activa, fecha_creacion)
SELECT id, 0, 90, TRUE, now() FROM segmentos_mora WHERE nombre = 'Mora Temprana';

INSERT INTO configuraciones_segmento (segmento_mora_id, dias_desde, dias_hasta, activa, fecha_creacion)
SELECT id, 91, 365, TRUE, now() FROM segmentos_mora WHERE nombre = 'Mora Inicial';

INSERT INTO configuraciones_segmento (segmento_mora_id, dias_desde, dias_hasta, activa, fecha_creacion)
SELECT id, 366, NULL, TRUE, now() FROM segmentos_mora WHERE nombre = 'Mora Tardía';
