CREATE TABLE contactos (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

   tipo_contacto VARCHAR(50) NOT NULL,

   valor VARCHAR(255) NOT NULL,

   es_de_contribuyente BOOLEAN NOT NULL,

   origen VARCHAR(100) NOT NULL,

   contribuyente_id BIGINT NOT NULL,

   CONSTRAINT fk_contacto_contribuyente
       FOREIGN KEY (contribuyente_id)
           REFERENCES contribuyentes(id)
);