CREATE TABLE padrones (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cm VARCHAR(100) NOT NULL UNIQUE,
      numero_padron VARCHAR(100) NOT NULL UNIQUE,
      tipo_padron VARCHAR(100),
      localidad VARCHAR(255),
      block VARCHAR(100),
      unidad VARCHAR(100),
      contribuyente_id BIGINT NOT NULL,

      CONSTRAINT fk_padron_contribuyente
          FOREIGN KEY (contribuyente_id)
              REFERENCES contribuyentes(id)
);